on:
  push:
    tags:
      - '*'
    branches:
      - master

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/ojichan:latest \
          --tag ghcr.io/$GITHUB_ACTOR/ojichan:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/ojichan:latest
          docker push ghcr.io/$GITHUB_ACTOR/ojichan:$(echo $GITHUB_SHA | head -c7)