on:
  push:
    tags:
      - '*'
    branches:
      - master

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: hmdyt.sakuracr.jp
          username: ${{ secrets.SAKURACLOUD_APPRUN_USER }}
          password: ${{ secrets.SAKURACLOUD_APPRUN_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build --tag hmdyt.sakuracr.jp/ojichan:latest \
          --tag hmdyt.sakuracr.jp/ojichan:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push hmdyt.sakuracr.jp/ojichan:latest
          docker push hmdyt.sakuracr.jp/ojichan:$(echo $GITHUB_SHA | head -c7)
